language: java

stages:
  - build
  - deploy
  - test


before_script:
  - chmod +x ./gradlew
  - echo `pwd`
  - export GRADLE_USER_HOME=`pwd`/.gradle
  - rm -f  .gradle/caches/modules-2/modules-2.lock
  - rm -fr .gradle/caches/*/plugin-resolution/

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

deploy:
    stage: deploy
    script:
        - git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/ppakseev.git
        - git push heroku master

build:
  stage: build
  script:
    - ./gradlew assemble
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 week
  only:
    - master

test:
  stage: test
  script:
    - ./gradlew check


after_script:
  - echo "End CI"
