language: java
jdk: oraclejdk8

before_install:
  - chmod +x ./gradlew
  - echo `pwd`
  - export GRADLE_USER_HOME=`pwd`/.gradle
  - rm -f  .gradle/caches/modules-2/modules-2.lock
  - rm -fr .gradle/caches/*/plugin-resolution/

cache:
  directories:
    - .gradle/wrapper
    - .gradle/caches
  
deploy:
  - provider: heroku
    api_key: $HEROKU_API_KEY
    app: ppakseev

build:
  stage: build
  script:
    - ./gradlew assemble
    - ./gradlew check
  artifacts:
    directories:
      - build/libs/*.jar
    expire_in: 1 week
  only:
    - master

after_script:
  - echo "End CI"
